on:
  workflow_dispatch:
  push:
    branches:
    - main
    - master
    - release/*
    
jobs:
  my_job:
    name: Deploy to LW
    runs-on: ubuntu-18.04
  
    steps:
    - name: cd and ls
      run: |
        ls -a

    - name: studies-lwftp-testing
      uses: allanalves23/ftp-action-studies@0.0.2
      with:
        host: "ftp.brqdomaintest1.hospedagemdesites.ws"
        user: "brqdomaintest1"
        password: "Pass123456789@"
        localDir: "."
        remoteDir: "public_html"
