on:
  workflow_dispatch:
  push:
    branches:
    - main
    - master
    - release/*
    
jobs:
  my_job:
    name: Deploy to LW
    runs-on: ubuntu-lastest
  
    steps:
    - name: Download files from the current repository
      uses: actions/checkout@v2

    - name: studies-lwftp-testing
      uses: allanalves23/ftp-action-studies@0.0.2
      with:
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USER }}
        password: ${{ secrets.PASS }}
        localDir: "."
        remoteDir: "public_html"
